version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  
  build:
    commands:
      - echo "=== Starting HTML validation tests ==="
      - pwd
      - ls -la
      - echo "=== Checking if index.html exists ==="
      - if [ -f "index.html" ]; then echo "✅ index.html found"; else echo "❌ index.html not found" && exit 1; fi
      - echo "=== Checking HTML basic structure ==="
      - if grep -q "<html>" index.html; then echo "✅ html tag found"; else echo "❌ Missing html tag" && exit 1; fi
      - if grep -q "<head>" index.html; then echo "✅ head tag found"; else echo "❌ Missing head tag" && exit 1; fi
      - if grep -q "<body>" index.html; then echo "✅ body tag found"; else echo "❌ Missing body tag" && exit 1; fi
      - echo "🎉 All HTML tests passed successfully!"

artifacts:
  files:
    - '**/*'
